const EmployersignupFields = [
  {
    labelText: "Email address:",
    labelFor: "email-address",
    id: "email-address",
    name: "email",
    type: "email",
    autoComplete: "email",
    isRequired: true,
    placeholder: "Email address",
  },
  {
    labelText: "Password:",
    labelFor: "password",
    id: "password",
    name: "password",
    type: "password",
    autoComplete: "current-password",
    isRequired: true,
    placeholder: "Password",
  },
  {
    labelText: "Confirm Password:",
    labelFor: "confirm-password",
    id: "confirm-password",
    name: "confirm-password",
    type: "password",
    autoComplete: "confirm-password",
    isRequired: true,
    placeholder: "Confirm Password",
  },
  {
    labelText: "Phone Number:",
    labelFor: "phone-number",
    id: "phone-number",
    name: "phone-number",
    type: "number",
    inputMode: "numeric",
    autoComplete: "phone-number",
    isRequired: true,
    placeholder: "Phone Number",
  },
  {
    labelText: "Company name:",
    labelFor: "Company-name",
    id: "Company-name",
    name: "Company-name",
    type: "text",
    autoComplete: "Company-name",
    isRequired: true,
    placeholder: "Company-name",
  },

  {
    labelText: "Company Address:",
    labelFor: "Company-address",
    id: "Company-address",
    name: "Company-address",
    type: "text",
    autoComplete: "Company-address",
    isRequired: true,
    placeholder: "Company Address",
  },
];

export { EmployersignupFields };
