const signupFields = [
  {
    labelText: "Username:",
    labelFor: "username",
    id: "username",
    name: "username",
    type: "text",
    autoComplete: "username",
    isRequired: true,
    placeholder: "Username",
  },
  {
    labelText: "Email address:",
    labelFor: "email",
    id: "email",
    name: "email",
    type: "email",
    autoComplete: "email",
    isRequired: true,
    placeholder: "Email address",
  },
  {
    labelText: "Password:",
    labelFor: "password",
    id: "password",
    name: "password",
    type: "password",
    autoComplete: "current-password",
    isRequired: true,
    placeholder: "Password",
  },
  {
    labelText: "Confirm Password:",
    labelFor: "confirm-password",
    id: "confirm-password",
    name: "confirm-password",
    type: "password",
    autoComplete: "confirm-password",
    isRequired: true,
    placeholder: "Confirm Password",
  },
  {
    labelText: "Phone Number:",
    labelFor: "phone-number",
    id: "phone-number",
    name: "phone-number",
    type: "number",
    inputMode: "numeric",
    autoComplete: "phone-number",
    isRequired: true,
    placeholder: "Phone Number",
  },
  {
    labelText: "Current Address:",
    labelFor: "current-address",
    id: "current-address",
    name: "current-address",
    type: "text",
    autoComplete: "current-address",
    isRequired: true,
    placeholder: "Current Address",
  },
  {
    labelText: "School:",
    labelFor: "School",
    id: "School",
    name: "School",
    type: "text",
    autoComplete: "School",
    isRequired: true,
    placeholder: "School",
  },
  {
    labelText: "School Address:",
    labelFor: "School-address",
    id: "School-address",
    name: "School-address",
    type: "text",
    autoComplete: "School-address",
    isRequired: true,
    placeholder: "School Address",
  },
];

export { signupFields };
