GET http://localhost:8081/api/users

###

GET http://localhost:8081/api/users/1

###

GET http://localhost:8081/api/users/register

###

GET http://localhost:8081/api/users/login

###

POST http://localhost:8081/api/todos
Content-Type: application/json

{
  "task": "Go Fishing",
  "isCompleted": false
}

### 

POST http://localhost:8081/api/todos
Content-Type: application/json


###

PUT http://localhost:8081/api/todos/2
Content-Type: application/json

{
  "task": "222",
  "isCompleted": true
}

### 

DELETE http://localhost:8081/api/users/1
