const EmployerSignupFields = [
  {
    id: "user_type",
    name: "user_type",
    type: "hidden",
    value: "employer",
  },
  {
    labelText: "Username:",
    labelFor: "Username",
    id: "username",
    name: "username",
    type: "text",
    autoComplete: "username",
    isRequired: true,
    placeholder: "Username",
  },
  {
    labelText: "Email address:",
    labelFor: "emailAddress",
    id: "email",
    name: "email",
    type: "email",
    autoComplete: "email",
    isRequired: true,
    placeholder: "Email address",
  },
  {
    labelText: "Password:",
    labelFor: "password",
    id: "password",
    name: "password",
    type: "password",
    autoComplete: "password",
    isRequired: true,
    placeholder: "Password",
  },
  {
    labelText: "Confirm Password:",
    labelFor: "confirm-password",
    id: "confirm-password",
    name: "confirm-password",
    type: "password",
    autoComplete: "confirm-password",
    isRequired: true,
    placeholder: "Confirm Password",
  },
  {
    labelText: "Employer Name:",
    labelFor: "employer-name",
    id: "employer-name",
    name: "employer-name",
    type: "text",
    autoComplete: "employer-name",
    isRequired: true,
    placeholder: "Employer Name",
  },
  {
    labelText: "Contact Number:",
    labelFor: "contact-number",
    id: "contact-number",
    name: "contact-number",
    type: "number",
    inputMode: "numeric",
    autoComplete: "contact-number",
    isRequired: true,
    placeholder: "Contact Number",
  },
  {
    labelText: "Company name:",
    labelFor: "company-name",
    id: "company-name",
    name: "company-name",
    type: "text",
    autoComplete: "company-name",
    isRequired: true,
    placeholder: "Company Name",
  },

  {
    labelText: "Company Address:",
    labelFor: "company-address",
    id: "company-address",
    name: "company-address",
    type: "text",
    autoComplete: "company-address",
    isRequired: true,
    placeholder: "Company Address",
  },
];

export { EmployerSignupFields };
